/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExitoRouteImport } from './routes/exito'
import { Route as PagoRouteImport } from './routes/pago'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExitoRoute = ExitoRouteImport.update({
  id: '/exito',
  path: '/exito',
  getParentRoute: () => rootRouteImport,
} as any)
const PagoRoute = PagoRouteImport.update({
  id: '/pago',
  path: '/pago',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exito': typeof ExitoRoute
  '/pago': typeof PagoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/exito': typeof ExitoRoute
  '/pago': typeof PagoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/exito': typeof ExitoRoute
  '/pago': typeof PagoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/exito' | '/pago'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/exito' | '/pago'
  id: '__root__' | '/' | '/exito' | '/pago'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExitoRoute: typeof ExitoRoute
  PagoRoute: typeof PagoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exito': {
      id: '/exito'
      path: '/exito'
      fullPath: '/exito'
      preLoaderRoute: typeof ExitoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pago': {
      id: '/pago'
      path: '/pago'
      fullPath: '/pago'
      preLoaderRoute: typeof PagoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExitoRoute: ExitoRoute,
  PagoRoute: PagoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
